site_name: My Spark Docs
site_url: https://charliey2.github.io/spark-docs/

docs_dir: spark-docs

theme:
  name: material
  
  palette:
    primary: custom
    scheme: slate
  
  features:
    - navigation.instant
    - navigation.instant.progress
    - content.tooltips
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: false
  - section-index

extra_css:
  - stylesheets/extra.css
  - stylesheets/flags.css

watch:
  - includes

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn