site_name: My Docs
site_url: https://example.com

theme:
  name: material
  
  palette:
    primary: custom
    scheme: slate
  
  features:
    - navigation.instant
    - navigation.instant.progress
    - content.tooltips
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css
  - stylesheets/flags.css

watch:
  - includes